### ISSUE TITLE
React Router Issue

### ISSUE THREAD

**Issue by bishakhdutta** [bishakhdutta/DateU#2]
Images not loading after routing 
I think the problem is the source url of the image is changing as i tried to open image in new tab it is not opening the correct url for the image

Though it will not be a problem after adding backend
Since the images will be fetched from server instead of local storage

**Comment by ankanroy-code** [comment]
when i change move the image folder from /public to /src AND load the image from index.js using an img tag it works. Should i move this knowledge forward, it might lead to some big component / core working change.

**Comment by bishakhdutta** [comment]
> when i move the image folder from /public to /src AND load the image from index.js using an img tag it works. Should i move this knowledge forward, it might lead to some big component / core working change.

Images must be in public folder

**Comment by ankanroy-code** [comment]
ok

**Comment by ankanroy-code** [comment]
it is not open from public i tried it, i opened an img tag in index.js ,it giving an build error

**Comment by bishakhdutta** [comment]
Issue solved
